class CfgPatches
{
	class DZ_Weapons_Firearms_UMP
	{
		units[]=
		{
			"UMP45"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Weapons_Firearms"
		};
	};
};
class Mode_Safe;
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class cfgWeapons
{
	class MilitaryRifle;
	class UMP_Base: MilitaryRifle
	{
		absorbency=0.1;
		scope=0;
		value=0;
		dexterity=3.2;
		optics=1;
		chamberSize=1;
		chamberedRound="";
		camberableFrom[]=
		{
			"Ammo_45FMJ"
		};
		magazines[]=
		{
			"M_UMP_25Rnd"
		};
		ejectType=1;
		modes[]=
		{
			"FullAuto"
		};
		lootTag[]=
		{
			"Military_west"
		};
		repairableWith=1;
		modelOptics="-";
		distanceZoomMin=100;
		distanceZoomMax=100;
		weight=2200;
		drySound[]=
		{
			"dz\sounds\weapons\firearms\m4a1\m4_dry",
			0.5,
			1,
			20
		};
		reloadMagazineSound[]=
		{
			"dz\sounds\weapons\firearms\ump45\ump45_reload",
			0.80000001,
			1,
			30
		};
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\DZ\anims\data\anim\sdr\ik\weapons\ump.rtm"
		};
		class FullAuto: Mode_FullAuto
		{
			begin1[]=
			{
				"dz\sounds\weapons\firearms\ump45\ump45_single_0",
				1,
				1,
				700
			};
			begin2[]=
			{
				"dz\sounds\weapons\firearms\ump45\ump45_single_1",
				1,
				1,
				700
			};
			begin3[]=
			{
				"dz\sounds\weapons\firearms\ump45\ump45_single_2",
				1,
				1,
				700
			};
			soundBegin[]=
			{
				"begin1",
				0.33333001,
				"begin2",
				0.33333001,
				"begin3",
				0.33333001
			};
			reloadTime=0.11;
			recoil="recoil_auto_primary_7outof10";
			recoilProne="recoil_auto_primary_prone_7outof10";
			dispersion=0.003;
			magazineSlot="magazine";
			beginSilenced_Pro[]=
			{
				"dz\sounds\weapons\firearms\mp5k\mp5Silenced",
				1,
				1,
				75
			};
			beginSilenced_HomeMade[]=
			{
				"dz\sounds\weapons\firearms\mp5k\mp5Silenced",
				1,
				1,
				100
			};
			soundBeginExt[]=
			{
				
				{
					"beginSilenced_Pro",
					1
				},
				
				{
					"beginSilenced_HomeMade",
					1
				}
			};
		};
		reloadAction="ReloadUMP";
		baseAttachments[]={};
		attachments[]=
		{
			"weaponFlashlight",
			"weaponOptics",
			"pistolMuzzle",
			"weaponWrap",
			"suppressorImpro"
		};
		hiddenSelections[]=
		{
			"camo"
		};
		class Damage
		{
			tex[]={};
			mat[]=
			{
				"DZ\weapons\firearms\UMP45\data\ump45.rvmat",
				"DZ\weapons\firearms\UMP45\data\ump45_damage.rvmat",
				"DZ\weapons\firearms\UMP45\data\ump45_destruct.rvmat"
			};
		};
	};
	class UMP45: UMP_Base
	{
		scope=2;
		displayName="UMP45";
		descriptionShort="The UMP is a sub-machine gun that has been adopted by various agencies such as the U.S. Customs and Border Protection. It was developed as a lighter and cheaper successor to the MP5. UMP is chambered for .45 ACP cartriges to provide more stopping power against unarmored targets (with slightly lower effectiveness at longer range) than the MP5. Cyclic rate of fire of UMP is 600 rounds/min which makes it one of the slower firing sub-machine guns on the market.";
		model="\dz\weapons\firearms\UMP45\ump.p3d";
		itemSize[]={4,3};
		hiddenSelectionsTextures[]=
		{
			"dz\weapons\firearms\UMP45\data\ump45_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"DZ\weapons\firearms\UMP45\data\ump45.rvmat"
		};
	};
};
